// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package catalog

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"fr": &dictionary{index: frIndex, data: frData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"actions":                24,
	"add_new_project":        0,
	"add_project":            10,
	"allow_insecure":         8,
	"allow_insecure_warning": 9,
	"check_time":             23,
	"confirm_delete":         30,
	"custom":                 6,
	"dashboard":              19,
	"days_remaining":         17,
	"delete":                 31,
	"domains":                13,
	"expired":                26,
	"expiry_date":            16,
	"failed":                 18,
	"history":                27,
	"host":                   2,
	"host_port":              21,
	"ip":                     14,
	"issuer":                 15,
	"never_checked":          25,
	"no_history_found":       11,
	"no_projects":            20,
	"port":                   7,
	"project_name":           1,
	"project_type":           22,
	"projects":               29,
	"refresh_datas":          28,
	"service_type":           3,
	"verification_date":      12,
	"with_auth_tls":          4,
	"with_starttls":          5,
}

var enIndex = []uint32{ // 33 elements
	// Entry 0 - 1F
	0x00000000, 0x00000010, 0x0000001d, 0x00000022,
	0x0000002f, 0x0000003f, 0x0000004f, 0x00000056,
	0x0000005b, 0x00000077, 0x000000db, 0x000000e7,
	0x000000f8, 0x0000010a, 0x00000112, 0x00000115,
	0x0000011c, 0x00000128, 0x00000137, 0x0000013e,
	0x00000148, 0x00000153, 0x0000015d, 0x0000016a,
	0x00000175, 0x0000017d, 0x0000018b, 0x00000193,
	0x0000019b, 0x000001a9, 0x000001b2, 0x000001e0,
	// Entry 20 - 3F
	0x000001e7,
} // Size: 156 bytes

const enData string = "" + // Size: 487 bytes
	"\x02Add new project\x02Project name\x02Host\x02Service type\x02(with aut" +
	"h TLS)\x02(with STARTTLS)\x02Custom\x02Port\x02Allow insecure certificat" +
	"es\x02Allow insecure certificates must be used for self-signed or invali" +
	"d certificates. Use with caution.\x02Add project\x02No history found\x02" +
	"Verification date\x02Domains\x02IP\x02Issuer\x02Expiry date\x02Days rema" +
	"ining\x02Failed\x02Dashboard\x02No project\x02Host:Port\x02Project type" +
	"\x02Check time\x02Actions\x02Never checked\x02expired\x02History\x02Refr" +
	"esh datas\x02Projects\x02Are you sure you want to delete this project?" +
	"\x02Delete"

var frIndex = []uint32{ // 33 elements
	// Entry 0 - 1F
	0x00000000, 0x0000001a, 0x00000028, 0x0000002e,
	0x0000003e, 0x0000004e, 0x0000005e, 0x0000006c,
	0x00000071, 0x0000009b, 0x000000ed, 0x000000ff,
	0x00000118, 0x00000130, 0x00000139, 0x0000013c,
	0x00000146, 0x00000150, 0x0000015f, 0x00000166,
	0x00000176, 0x00000185, 0x00000190, 0x00000195,
	0x000001ab, 0x000001b3, 0x000001c4, 0x000001cc,
	0x000001d7, 0x000001f0, 0x00000202, 0x00000253,
	// Entry 20 - 3F
	0x0000025d,
} // Size: 156 bytes

const frData string = "" + // Size: 605 bytes
	"\x02Ajouter un nouveau projet\x02Nom du projet\x02Hôte\x02Type de servic" +
	"e\x02(avec AUTH TLS)\x02(avec STARTTLS)\x02Personnalisé\x02Port\x02Autor" +
	"iser les certificats non sécurisés\x02Pour les certificats auto-signés o" +
	"u non sécurisés. À utiliser avec prudence !\x02Ajouter le projet\x02Aucu" +
	"n historique trouvé\x02Dernière vérification\x02Domaines\x02IP\x02Émette" +
	"ur\x02Expire le\x02Jours restants\x02Échec\x02Tableau de bord\x02Aucun p" +
	"rojet !\x02Hôte:Port\x02Type\x02Date de vérification\x02Actions\x02Jamai" +
	"s vérifié\x02Expiré\x02Historique\x02Rafraîchir les données\x02Liste des" +
	" projets\x02Êtes vous sûr de vouloir supprimer ce projet et l'ensemble d" +
	"e son historique ?\x02Supprimer"

	// Total table size 1404 bytes (1KiB); checksum: 28F18B00
